local func = require "jct/func"
local coor = require "jct/coor"
local pipe = require "jct/pipe"
local arc = require "jct/coorarc"
local line = require "jct/coorline"
local jct = require "jct2"
local quat = require "jct/quaternion"
local livetext = require "jct/livetext"
local dump = require "luadump"

local insert = table.insert

local preProcessAdd = function(modules, change, classedModules, info)
    local maxId = func.max(func.keys(classedModules))
end

local preProcessRemove = function(modules, change, classedModules, info)
    end

local slotSetup = function(params, result, slotId)
    local module = params.modules[slotId]
    
    table.insert(result.slots, {
        id = slotId,
        transf = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1},
        type = "jct_struct",
        spacing = {0, 0, 0, 0}
    })

end

local fzGen = function(initHeight, finalHeight)
    return function(initRad, finalRad)
        local ln = line.byPtPt(
            coor.xy(initRad, initHeight),
            coor.xy(finalRad, finalHeight)
        )
        return function(rad) return (ln - line.byVecPt(coor.xy(0, 1), coor.xy(rad, 0))).y end
    end
end

local fsGen = function(slope)
    return function(initRad, finalRad) return function(_) return slope end end
end

local ptXSelector = function(lhs, rhs) return lhs:length2() < rhs:length2() end

local function checkRange(a, b, c, d)
    return (a <= b and b <= c and c <= d) or (a >= b and b >= c and c >= d)
end

local function gridization(pos, data)
    local x, y, z = pos.x, pos.y, pos.z
    local slotId = data.grid[z][y][x]
    
    local m = data.modules[slotId]
    local info = m.info
    -- dump()(info)
    if x == 0 and (y == 1 or y == -1) then
        local radius = info.radius
        local xRad = info.xRad
        -- if z == 0 then
        --     local fz = fzGen(0, 0)
        --     local fs = fsGen(0)
        --     info.arcPacker = jct.arcPacker(radius, -xRad * 0.5, fz, fs)
        -- else
        local fz = fzGen(info.height, info.height)
        local fs = fsGen(0)
        info.arcPacker = jct.arcPacker(radius, xRad * 0.5, fz, fs)
        -- end
        info.offset = 0
    elseif x == 0 and y > 1 then
        local refSlotId = data.grid[z][y - 1][0]
        info.arcPacker = data.modules[refSlotId].info.arcPacker
        info.offset = 0
    elseif x == 0 and y < -1 then
        local refSlotId = data.grid[z][y + 1][0]
        info.arcPacker = data.modules[refSlotId].info.arcPacker
        info.offset = 0
    elseif x < 0 then
        local refSlotId = data.grid[z][y][x + 1]
        local ref = data.modules[refSlotId]
        info.arcPacker = ref.info.arcPacker
        info.offset = ref.info.offset - ref.metadata.width * 0.5 - m.metadata.width * 0.5
    elseif x > 0 then
        local refSlotId = data.grid[z][y][x - 1]
        local ref = data.modules[refSlotId]
        info.arcPacker = ref.info.arcPacker
        info.offset = ref.info.offset + ref.metadata.width * 0.5 + m.metadata.width * 0.5
    end
    
    coroutine.yield()
    local arc, initRad, fn = info.arcPacker(info.offset)(m.metadata.width)
    info.baseArcs = {arc = arc, initRad = initRad, fn = fn}
    
    coroutine.yield()
    local z1Max = data.modules[data.grid[1][y][func.max(func.keys(data.grid[1][y]))]].info
    local z1Min = data.modules[data.grid[1][y][func.min(func.keys(data.grid[1][y]))]].info
    local z0Max = data.modules[data.grid[0][y][func.max(func.keys(data.grid[0][y]))]].info
    local z0Min = data.modules[data.grid[0][y][func.min(func.keys(data.grid[0][y]))]].info
    if x == 0 and (y == 1 or y == -1) then
        if y == 1 then
            local ptXSup = func.min(z0Min.baseArcs.arc[1] - z1Max.baseArcs.arc[2], ptXSelector)
            info.baseArcs.ptXSup = ptXSup
        else
            local ptXSup = func.min(z0Max.baseArcs.arc[2] - z1Min.baseArcs.arc[1], ptXSelector)
            info.baseArcs.ptXSup = ptXSup
        end
        info.baseArcs.fn = info.baseArcs.fn(info.baseArcs.ptXSup)
        info.fnArc = info.baseArcs.fn(info.baseArcs.ptXSup)
    elseif x < 0 then
        local refSlotId = data.grid[z][y][x + 1]
        local ref = data.modules[refSlotId].info
        
        info.baseArcs.ptXSup = ref.baseArcs.ptXSup
        info.baseArcs.fn = info.baseArcs.fn(info.baseArcs.ptXSup)
        
        info.fnArc = info.baseArcs.fn(info.baseArcs.ptXSup)
    elseif x > 0 then
        local refSlotId = data.grid[z][y][x - 1]
        local ref = data.modules[refSlotId].info
        
        info.baseArcs.ptXSup = ref.baseArcs.ptXSup
        info.baseArcs.fn = info.baseArcs.fn(info.baseArcs.ptXSup)
        
        info.fnArc = info.baseArcs.fn(info.baseArcs.ptXSup)
    else
        
        end
    info.arc = info.fnArc(0)
    dump()(slotId)
    dump()("x")
    coroutine.yield()
    info.baseArcs = nil
    info.arcs = {
        info.arc
    }
    if z == 0 then
        local ptXZ1Min = func.min(info.arc - z1Min.info.arc, ptXSelector)
        local ptXZ1Max = func.min(info.arc - z1Max.info.arc, ptXSelector)
        
        local radZ1Min = info.arc:rad(ptXZ1Min)
        local radZ1Max = info.arc:rad(ptXZ1Max)
        local radInf = info.arc.inf
        local radSup = info.arc.sup
        
        if y > 0 then
            if checkRange(radZ1Max, radInf, radZ1Min, radSup) then
                info.arcs = {
                    info.arc:withLimits({inf = radZ1Min, sup = radSup})
                }
            else
                info.arcs = {
                    info.arc
                }
            end
        else
            info.arcs = {
                info.arc
            }
        end
    else
        info.arcs = {
            info.arc
        }
    end

    dump()(slotId)
    dump()(info)
end

---@param modules table<slotid, module>
---@param classified classified_modules
---@param slotId slotid
---@param params any
local postClassify = function(modules, classified, slotId, params)
    modules[slotId].info.height = modules[slotId].info.pos.z == 1 and params.tunnelHeight or 0
    modules[slotId].info.xRad = params.xRad
    
    modules[slotId].info.transf = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1}
    
    if modules[slotId].info.straight then
        modules[slotId].info.radius = jct.infi
    end
end

function data()
    return {
        preProcessAdd = preProcessAdd,
        preProcessRemove = preProcessRemove,
        slotSetup = slotSetup,
        preClassify = jct.preClassify,
        postClassify = postClassify,
        getModelsFn = function(params)
            return {}
        end,
        gridization = gridization
    }

end
